spring:
  profiles:
    active: 
      - dev
---
spring:
  profiles: dev
  application:
    name: cloud2020-config-atguigu-dev

---
spring:
  profiles: test
  application:
    name: cloud2020-config-atguigu-test
#保存为测试环境